trigger:
  batch: true
  branches:
    include:
      - master
      - develop

resources:
  repositories:
    - repository: GitHub
      type: github
      name: 'NavisCarrierSolutions/BlueTracker.SDK.Performance'
      endpoint: 'NavisCarrierSolutions'
    - repository: PipelineTemplates
      name: DevOps/Pipeline-Templates
      type: git
      endpoint: Pipeline-Templates # Service connectionname in the Azure DevOps GUI

stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: 'Build'
        pool: 'Fleet-Build'
        strategy:
          matrix:
            Release-Any:
              Platform: 'Any CPU'
              BuildConfiguration: 'Release'
        workspace:
          clean: outputs

        steps:
          - checkout: self
            clean: true

          - template: GitVersion/gitversion.v1.yml@PipelineTemplates
            parameters:
              updateAssemblyInfo: true

          - task: NuGetToolInstaller@1
            displayName: 'Use NuGet 5.6.0'
            inputs:
              versionSpec: 5.6.0

          - task: NuGetCommand@2
            displayName: 'NuGet restore'
            inputs:
              restoreSolution: BlueTracker.SDK.sln

          - task: VSBuild@1
            displayName: 'Build solution BlueTracker.SDK.sln'
            inputs:
              solution: BlueTracker.SDK.sln
              platform: '$(Platform)'
              configuration: '$(BuildConfiguration)'

          - task: MSBuild@1
            displayName: 'NuGet package'
            inputs:
              solution: BlueTracker.SDK.sln
              platform: '$(Platform)'
              configuration: '$(BuildConfiguration)'
              msbuildArguments: '/t:pack /p:PackageOutputPath="$(Build.ArtifactStagingDirectory)" /p:NoPackageAnalysis=true /p:PackageVersion=$(GitVersion.FullSemVer)'
              maximumCpuCount: true

          - task: PublishBuildArtifacts@1
            displayName: 'Master Branch: Publish Artifact'
            inputs:
              PathtoPublish: '$(Build.Artifactstagingdirectory)'

  - stage: DeployToAzure
    displayName: 'Deploy to Azure DevOps'

    jobs:
      - deployment: Deploy
        displayName: 'Deploying'
        pool: 'Fleet-Build'
        environment: azure
        workspace:
          clean: all

        strategy:
          runOnce:
            deploy:
              steps:
                - task: NuGetToolInstaller@1
                  displayName: 'Use NuGet 5.6.0'
                  inputs:
                    versionSpec: 5.6.0
                    checkLatest: true

                - task: NuGetCommand@2
                  displayName: 'NuGet push'
                  inputs:
                    command: push
                    packagesToPush: '$(Pipeline.Workspace)\drop\*.nupkg'
                    publishVstsFeed: 'c69ffa3a-dc58-431c-afe0-12f465fcb265'
                    allowPackageConflicts: true

  - stage: DeployToCloud
    displayName: 'Deploy to NCVS-Cloud'

    jobs:
      - deployment: Deploy
        displayName: 'Deploying'
        pool: 'Fleet-Build'
        environment: azure
        workspace:
          clean: all

        strategy:
          runOnce:
            deploy:
              steps:
                - task: NuGetToolInstaller@1
                  displayName: 'Use NuGet 5.6.0'
                  inputs:
                    versionSpec: 5.6.0
                    checkLatest: true

                - task: NuGetCommand@2
                  displayName: 'NuGet push'
                  inputs:
                    command: 'push'
                    packagesToPush: '$(Pipeline.Workspace)\drop\*.nupkg'
                    nuGetFeedType: 'external'
                    publishFeedCredentials: 'NCVS-Cloud Shared'

  - stage: DeployToNuget
    displayName: 'Deploy to Nuget.org'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

    jobs:
      - deployment: Deploy
        displayName: 'Deploying'
        pool: 'Fleet-Build'
        environment: nuget
        workspace:
          clean: all

        strategy:
          runOnce:
            deploy:
              steps:
                - task: NuGetToolInstaller@1
                  displayName: 'Use NuGet 5.6.0'
                  inputs:
                    versionSpec: 5.6.0
                    checkLatest: true

                - task: NuGetCommand@2
                  displayName: 'NuGet push'
                  inputs:
                    command: push
                    packagesToPush: '$(Pipeline.Workspace)\drop\*.nupkg'
                    nuGetFeedType: external
                    publishFeedCredentials: www.nuget.org-API-key
